version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "moralpain-api-typedb"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-96uywyvqhr1g"
s3_prefix = "moralpain-api-typedb"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
