AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  sam

  Sample SAM Template for sam

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Parameters: 
  ec2IPAddress: 
    Type: String
    Default: cfn-ec2-vpc-sg::EC2InstanceIP
  privateSubnet1: 
    Type: String
    Default: cfn-ec2-vpc-sg::PrivateSubnet1
  privateSubnet2: 
    Type: String
    Default: cfn-ec2-vpc-sg::PrivateSubnet2

Resources:
  TypeDBGetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: GetSubmissions
      CodeUri: MoralPainFunctions
      Policies: 
       - AmazonVPCFullAccess
      Handler: edu.uva.cs.moralpain.TypeDBGet::handleRequest
      Runtime: java11
      VpcConfig:
        # SecurityGroupIds:
        #   Fn::ImportValue: !Ref securityGroup
        # SubnetIds:
        #   Fn::ImportValue:
        #     - !Ref privateSubnet1
        #     - !Ref privateSubnet2
        SecurityGroupIds:
          - !ImportValue cfn-ec2-vpc-sg-SGID1
        SubnetIds:
          - !ImportValue cfn-ec2-vpc-sg-privatesubnet1
          - !ImportValue cfn-ec2-vpc-sg-privatesubnet2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          EC2_IP_ADDRESS: !ImportValue cfn-ec2-vpc-sg-ec2instanceip
          DATABASE_NAME: test
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /submissions
            Method: get
            
  TypeDBPostFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: PostSubmissions
      CodeUri: MoralPainFunctions
      Policies: 
       - AmazonVPCFullAccess
      Handler: edu.uva.cs.moralpain.TypeDBPost::handleRequest
      Runtime: java11
      VpcConfig:
        # SecurityGroupIds:
        #   - Fn::ImportValue
        #     - !Ref securityGroup
        # SubnetIds:
        #   - Fn::ImportValue
        #     - !Ref privateSubnet1
        #   - Fn::ImportValue
        #     - !Ref privateSubnet2
        SecurityGroupIds:
          # - !ImportValue cfn-ec2-vpc-sg-SGID2
          - !ImportValue cfn-ec2-vpc-sg-SGID1
        SubnetIds:
          - !ImportValue cfn-ec2-vpc-sg-privatesubnet1
          - !ImportValue cfn-ec2-vpc-sg-privatesubnet2
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          EC2_IP_ADDRESS: !ImportValue cfn-ec2-vpc-sg-ec2instanceip
          DATABASE_NAME: test
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /submissions
            Method: post
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  TypeDBGetApi:
    Description: "API Gateway endpoint URL for Prod stage for TypeDB Get function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/submissions/"
  TypeDBGetFunction:
    Description: "TypeDB Get Lambda Function ARN"
    Value: !GetAtt TypeDBGetFunction.Arn
  TypeDBGetFunctionIamRole:
    Description: "Implicit IAM Role created for TypeDB Get function"
    Value: !GetAtt TypeDBGetFunctionRole.Arn
